'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My

    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0"), _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase

        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()), MySettings)

#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region

        Public Shared ReadOnly Property [Default]() As MySettings
            Get

#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("Host=hon03nt;port=5432;database=LogisticDb")> _
        Public Property con1() As String
            Get
                Return CType(Me("con1"), String)
            End Get
            Set(value As String)
                Me("con1") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("Host=hon14nt;port=5432;database=LogisticDb")> _
        Public Property con2() As String
            Get
                Return CType(Me("con2"), String)
            End Get
            Set(value As String)
                Me("con2") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("Host=localhost;port=5432;database=LogisticDb20150120")> _
        Public Property temp() As String
            Get
                Return CType(Me("temp"), String)
            End Get
            Set(value As String)
                Me("temp") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("Black")> _
        Public Property MenuStripGradientBegin() As Global.System.Drawing.Color
            Get
                Return CType(Me("MenuStripGradientBegin"), Global.System.Drawing.Color)
            End Get
            Set(value As Global.System.Drawing.Color)
                Me("MenuStripGradientBegin") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("DimGray")> _
        Public Property MenuStripGradientEnd() As Global.System.Drawing.Color
            Get
                Return CType(Me("MenuStripGradientEnd"), Global.System.Drawing.Color)
            End Get
            Set(value As Global.System.Drawing.Color)
                Me("MenuStripGradientEnd") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("WhiteSmoke")> _
        Public Property MenuStripForeColor() As Global.System.Drawing.Color
            Get
                Return CType(Me("MenuStripForeColor"), Global.System.Drawing.Color)
            End Get
            Set(value As Global.System.Drawing.Color)
                Me("MenuStripForeColor") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("Maroon")> _
        Public Property MenuItemPressedGradientBegin() As Global.System.Drawing.Color
            Get
                Return CType(Me("MenuItemPressedGradientBegin"), Global.System.Drawing.Color)
            End Get
            Set(value As Global.System.Drawing.Color)
                Me("MenuItemPressedGradientBegin") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("Maroon")> _
        Public Property MenuItemPressedGradientMiddle() As Global.System.Drawing.Color
            Get
                Return CType(Me("MenuItemPressedGradientMiddle"), Global.System.Drawing.Color)
            End Get
            Set(value As Global.System.Drawing.Color)
                Me("MenuItemPressedGradientMiddle") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("Silver")> _
        Public Property MenuItemPressedGradientEnd() As Global.System.Drawing.Color
            Get
                Return CType(Me("MenuItemPressedGradientEnd"), Global.System.Drawing.Color)
            End Get
            Set(value As Global.System.Drawing.Color)
                Me("MenuItemPressedGradientEnd") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("Black")> _
        Public Property MenuItemSelectedGradientBegin() As Global.System.Drawing.Color
            Get
                Return CType(Me("MenuItemSelectedGradientBegin"), Global.System.Drawing.Color)
            End Get
            Set(value As Global.System.Drawing.Color)
                Me("MenuItemSelectedGradientBegin") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("Black")> _
        Public Property MenuItemSelectedGradientEnd() As Global.System.Drawing.Color
            Get
                Return CType(Me("MenuItemSelectedGradientEnd"), Global.System.Drawing.Color)
            End Get
            Set(value As Global.System.Drawing.Color)
                Me("MenuItemSelectedGradientEnd") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("Black")> _
        Public Property MenuItemSelected() As Global.System.Drawing.Color
            Get
                Return CType(Me("MenuItemSelected"), Global.System.Drawing.Color)
            End Get
            Set(value As Global.System.Drawing.Color)
                Me("MenuItemSelected") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("Maroon")> _
        Public Property ImageMarginGradientBegin() As Global.System.Drawing.Color
            Get
                Return CType(Me("ImageMarginGradientBegin"), Global.System.Drawing.Color)
            End Get
            Set(value As Global.System.Drawing.Color)
                Me("ImageMarginGradientBegin") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("WhiteSmoke")> _
        Public Property ImageMarginGradientMiddle() As Global.System.Drawing.Color
            Get
                Return CType(Me("ImageMarginGradientMiddle"), Global.System.Drawing.Color)
            End Get
            Set(value As Global.System.Drawing.Color)
                Me("ImageMarginGradientMiddle") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("WhiteSmoke")> _
        Public Property ImageMarginGradientEnd() As Global.System.Drawing.Color
            Get
                Return CType(Me("ImageMarginGradientEnd"), Global.System.Drawing.Color)
            End Get
            Set(value As Global.System.Drawing.Color)
                Me("ImageMarginGradientEnd") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("Black")> _
        Public Property MenuBorder() As Global.System.Drawing.Color
            Get
                Return CType(Me("MenuBorder"), Global.System.Drawing.Color)
            End Get
            Set(value As Global.System.Drawing.Color)
                Me("MenuBorder") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("Black")> _
        Public Property MenuItemBorder() As Global.System.Drawing.Color
            Get
                Return CType(Me("MenuItemBorder"), Global.System.Drawing.Color)
            End Get
            Set(value As Global.System.Drawing.Color)
                Me("MenuItemBorder") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("Black")> _
        Public Property ToolStripBorder() As Global.System.Drawing.Color
            Get
                Return CType(Me("ToolStripBorder"), Global.System.Drawing.Color)
            End Get
            Set(value As Global.System.Drawing.Color)
                Me("ToolStripBorder") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("Maroon")> _
        Public Property ToolStripContentPanelGradientBegin() As Global.System.Drawing.Color
            Get
                Return CType(Me("ToolStripContentPanelGradientBegin"), Global.System.Drawing.Color)
            End Get
            Set(value As Global.System.Drawing.Color)
                Me("ToolStripContentPanelGradientBegin") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("HighlightText")> _
        Public Property ToolStripContentPanelGradientEnd() As Global.System.Drawing.Color
            Get
                Return CType(Me("ToolStripContentPanelGradientEnd"), Global.System.Drawing.Color)
            End Get
            Set(value As Global.System.Drawing.Color)
                Me("ToolStripContentPanelGradientEnd") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("LightGray")> _
        Public Property ToolStripDropDownBackground() As Global.System.Drawing.Color
            Get
                Return CType(Me("ToolStripDropDownBackground"), Global.System.Drawing.Color)
            End Get
            Set(value As Global.System.Drawing.Color)
                Me("ToolStripDropDownBackground") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("HighlightText")> _
        Public Property ToolStripGradientBegin() As Global.System.Drawing.Color
            Get
                Return CType(Me("ToolStripGradientBegin"), Global.System.Drawing.Color)
            End Get
            Set(value As Global.System.Drawing.Color)
                Me("ToolStripGradientBegin") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("HighlightText")> _
        Public Property ToolStripGradientMiddle() As Global.System.Drawing.Color
            Get
                Return CType(Me("ToolStripGradientMiddle"), Global.System.Drawing.Color)
            End Get
            Set(value As Global.System.Drawing.Color)
                Me("ToolStripGradientMiddle") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("HighlightText")> _
        Public Property ToolStripGradientEnd() As Global.System.Drawing.Color
            Get
                Return CType(Me("ToolStripGradientEnd"), Global.System.Drawing.Color)
            End Get
            Set(value As Global.System.Drawing.Color)
                Me("ToolStripGradientEnd") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("Black")> _
        Public Property StatusStripGradientBegin() As Global.System.Drawing.Color
            Get
                Return CType(Me("StatusStripGradientBegin"), Global.System.Drawing.Color)
            End Get
            Set(value As Global.System.Drawing.Color)
                Me("StatusStripGradientBegin") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("DimGray")> _
        Public Property StatusStripGradientEnd() As Global.System.Drawing.Color
            Get
                Return CType(Me("StatusStripGradientEnd"), Global.System.Drawing.Color)
            End Get
            Set(value As Global.System.Drawing.Color)
                Me("StatusStripGradientEnd") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("Black")> _
        Public Property ToolStripForeColor() As Global.System.Drawing.Color
            Get
                Return CType(Me("ToolStripForeColor"), Global.System.Drawing.Color)
            End Get
            Set(value As Global.System.Drawing.Color)
                Me("ToolStripForeColor") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("WhiteSmoke")> _
        Public Property StatusStripForeColor() As Global.System.Drawing.Color
            Get
                Return CType(Me("StatusStripForeColor"), Global.System.Drawing.Color)
            End Get
            Set(value As Global.System.Drawing.Color)
                Me("StatusStripForeColor") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("Gold")> _
        Public Property ToolStripPanelGradientBegin() As Global.System.Drawing.Color
            Get
                Return CType(Me("ToolStripPanelGradientBegin"), Global.System.Drawing.Color)
            End Get
            Set(value As Global.System.Drawing.Color)
                Me("ToolStripPanelGradientBegin") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("InactiveCaption")> _
        Public Property ToolStripPanelGradientEnd() As Global.System.Drawing.Color
            Get
                Return CType(Me("ToolStripPanelGradientEnd"), Global.System.Drawing.Color)
            End Get
            Set(value As Global.System.Drawing.Color)
                Me("ToolStripPanelGradientEnd") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("ODBC;DSN=PostgreSQLhon03nt;")> _
        Public Property oExCon() As String
            Get
                Return CType(Me("oExCon"), String)
            End Get
            Set(value As String)
                Me("oExCon") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("ODBC;DSN=PostgreSQLhon03nt;")> _
        Public Property oExConLive() As String
            Get
                Return CType(Me("oExConLive"), String)
            End Get
            Set(value As String)
                Me("oExConLive") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("ODBC;DSN=PostgreSQL30;")> _
        Public Property oExConTest() As String
            Get
                Return CType(Me("oExConTest"), String)
            End Get
            Set(value As String)
                Me("oExConTest") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("Host=hon14nt;port=5432;database=LogisticDb")> _
        Public Property con3() As String
            Get
                Return CType(Me("con3"), String)
            End Get
            Set(value As String)
                Me("con3") = value
            End Set
        End Property

        <Global.System.Configuration.ApplicationScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString), _
         Global.System.Configuration.DefaultSettingValueAttribute("Host=hon14nt;port=5432;database=LogisticDb;commandTimeout=1000;Timeout=1000;")> _
        Public ReadOnly Property connectionstring1() As String
            Get
                Return CType(Me("connectionstring1"), String)
            End Get
        End Property

        <Global.System.Configuration.ApplicationScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString), _
         Global.System.Configuration.DefaultSettingValueAttribute("Host=hon14nt;port=5432;database=LogisticDb;commandTimeout=1000;Timeout=1000;")> _
        Public ReadOnly Property ConnectionString2() As String
            Get
                Return CType(Me("ConnectionString2"), String)
            End Get
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.DJLib.My.MySettings
            Get
                Return Global.DJLib.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
